language: node_js
node_js:
- 'node'
notifications:
  email:
  - howardc93@gmail.com
  - aqc2109@columbia.edu
  - mjr127@case.edu
# don't build master since that's the deployment branch
branches:
  except:
  - master
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: dev
  script: bash scripts/deploy.sh
